FROM ruby:2.3-alpine
RUN apk add --update \
    alpine-sdk \
    sqlite-dev \
    nodejs

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

RUN gem install mailcatcher

CMD mailcatcher -f --ip 0.0.0.0 --smtp-port 1025 --http-port 1080
